-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Affiliated_stores"
(
    store_code character varying(15) COLLATE pg_catalog."default" NOT NULL,
    company_registration_num character varying(10) NOT NULL,
    store_name character varying(7) COLLATE pg_catalog."default" NOT NULL,
    email character varying(15) COLLATE pg_catalog."default" NOT NULL,
    pw character varying(15) COLLATE pg_catalog."default" NOT NULL,
    phone_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT advertiser_pkey PRIMARY KEY (store_code)
);

COMMENT ON TABLE public."Affiliated_stores"
    IS '제휴가맹점';

CREATE TABLE IF NOT EXISTS public.advertisement_application
(
    ad_code character varying(6) NOT NULL,
    company_code character varying(6) COLLATE pg_catalog."default" NOT NULL,
    group_id character varying(6) COLLATE pg_catalog."default" NOT NULL,
    ad_title character varying(20) COLLATE pg_catalog."default" NOT NULL,
    ad_text character varying(200) COLLATE pg_catalog."default" NOT NULL,
    ad_category character varying(15) COLLATE pg_catalog."default" NOT NULL,
    image_url character varying(200) COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    deadline date NOT NULL,
    CONSTRAINT advertising_pkey PRIMARY KEY (ad_code)
);

CREATE TABLE IF NOT EXISTS public.customer_group
(
    group_id character varying(6) COLLATE pg_catalog."default" NOT NULL,
    age_range integer NOT NULL,
    gender character varying(1) COLLATE pg_catalog."default" NOT NULL,
    cons_category character varying(10) COLLATE pg_catalog."default" NOT NULL,
    region_name character varying(6) COLLATE pg_catalog."default",
    CONSTRAINT customer_group_pkey PRIMARY KEY (group_id)
);

CREATE TABLE IF NOT EXISTS public.report
(
    ad_id character varying(8) COLLATE pg_catalog."default" NOT NULL,
    group_id character varying(6) COLLATE pg_catalog."default" NOT NULL,
    click_num integer NOT NULL,
    click_per integer,
    benefit integer NOT NULL,
    benefit_per integer,
    preference integer,
    CONSTRAINT report_pkey PRIMARY KEY (ad_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.member
(
    "member_ID" character varying(8) NOT NULL,
    mem_age_range integer,
    mem_gender character varying(1),
    mem_job character varying(10),
    avg_assets integer,
    mem_region_name character varying(8),
    PRIMARY KEY ("member_ID")
);

CREATE TABLE IF NOT EXISTS public.per_cons_history
(
    payment_code character varying(6) NOT NULL,
    "member_ID" character varying(6) NOT NULL,
    pay_date date,
    pay_method "char" NOT NULL,
    pay_store_name "char" NOT NULL,
    pay_region_name "char" NOT NULL,
    pay_category "char" NOT NULL,
    pay_amount integer,
    PRIMARY KEY (payment_code)
);

COMMENT ON TABLE public.per_cons_history
    IS '개인소비내역';

CREATE TABLE IF NOT EXISTS public.personal_ad
(
    "member_ID" character varying(6) NOT NULL,
    "group_ID" character varying(6) NOT NULL,
    ad_code date NOT NULL,
    click_per_num integer NOT NULL,
    visit_date date NOT NULL,
    PRIMARY KEY ("group_ID", "member_ID")
);

COMMENT ON TABLE public.personal_ad
    IS '개인별 광고';

ALTER TABLE IF EXISTS public.advertisement_application
    ADD CONSTRAINT advertising_company_id_fkey FOREIGN KEY (company_code)
    REFERENCES public."Affiliated_stores" (store_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.advertisement_application
    ADD CONSTRAINT advertising_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES public.customer_group (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT report_ad_id_fkey FOREIGN KEY (ad_id)
    REFERENCES public.advertisement_application (ad_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT report_group_id_fkey FOREIGN KEY (group_id)
    REFERENCES public.customer_group (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.per_cons_history
    ADD CONSTRAINT "member_ID" FOREIGN KEY ("member_ID")
    REFERENCES public.member ("member_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personal_ad
    ADD FOREIGN KEY ("group_ID")
    REFERENCES public.customer_group (group_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personal_ad
    ADD FOREIGN KEY ("member_ID")
    REFERENCES public.member ("member_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.personal_ad
    ADD FOREIGN KEY (ad_code)
    REFERENCES public.advertisement_application (ad_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;